<a href="https://colab.research.google.com/github/2303A52080/GenrativeAI/blob/main/Assignment_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adadelta
from tensorflow.keras.utils import to_categorical



data = pd.read_csv("winequality-red.csv")
X, y = data.drop('quality', axis=1).values, data['quality'].values

num_classes = len(np.unique(y))
y = y - min(y)

y_categorical = to_categorical(y, num_classes=num_classes)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_categorical, test_size=0.2, random_state=42)

# Build and train ANN model
model = Sequential([
    Dense(16, input_dim=X_train.shape[1], activation='relu'),
    Dense(20, activation='relu'),
    Dense(25, activation='relu'),
    Dense(10, activation='relu'),
    Dense(num_classes, activation='softmax')
])
model.compile(optimizer=Adadelta(), loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=50, batch_size=64, validation_split=0.2)
model.save("wine_quality_model.h5")

# Evaluate and calculate metrics
model = load_model("wine_quality_model.h5")
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")
y_pred = np.argmax(model.predict(X_test), axis=-1)
y_test_labels = np.argmax(y_test, axis=-1)
print("Confusion Matrix:\n", confusion_matrix(y_test_labels, y_pred))
print("Classification Report:\n", classification_report(y_test_labels, y_pred, zero_division=1))

# Deploy and predict quality
def predict_quality(input_data):
    model = load_model("wine_quality_model.h5")
    input_data = scaler.transform(np.array(input_data).reshape(1, -1))
    prediction = np.argmax(model.predict(input_data), axis=-1)
    return prediction[0] + min(data['quality'])

# Example usage
sample_data = [7.4, 0.7, 0.0, 1.9, 0.076, 11, 34, 0.9978, 3.51, 0.56, 9.4]
print("Predicted Quality:", predict_quality(sample_data))


Epoch 1/50


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


16/16 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.1411 - loss: 1.8758 - val_accuracy: 0.1133 - val_loss: 1.8813
Epoch 2/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1163 - loss: 1.8816 - val_accuracy: 0.1133 - val_loss: 1.8811
Epoch 3/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1178 - loss: 1.8710 - val_accuracy: 0.1133 - val_loss: 1.8808
Epoch 4/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1242 - loss: 1.8737 - val_accuracy: 0.1133 - val_loss: 1.8806
Epoch 5/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1329 - loss: 1.8726 - val_accuracy: 0.1133 - val_loss: 1.8803
Epoch 6/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1333 - loss: 1.8705 - val_accuracy: 0.1133 - val_loss: 1.8800
Epoch 7/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1180 - loss: 1.8780 - val_accuracy: 0.1133 - val_loss: 1.8798
Epoch 8/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1356 - loss: 1.8648 - val_accuracy: 0.1133 - val_loss: 1.8795
Ep

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1029 - loss: 1.8713  
Test Accuracy: 0.1063
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
Confusion Matrix:
 [[ 0  0  0  0  1  0]
 [ 1  3  0  0  6  0]
 [18 52  4  3 53  0]
 [13 26 11  3 79  0]
 [ 3  4 11  0 24  0]
 [ 0  0  0  0  5  0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.04      0.30      0.06        10
           2       0.15      0.03      0.05       130
           3       0.50      0.02      0.04       132
           4       0.14      0.57      0.23        42
           5       1.00      0.00      0.00         5

    accuracy                           0.11       320
   macro avg       0.31      0.15      0.06       320
weighted avg       0.30      0.11      0.07       320



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step
Predicted Quality: 7
